default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: qwer1234
  host: localhost

development:
  <<: *default
  database: rails_5_test

test:
  <<: *default
  database: rails_5_test_test

production:
  <<: *default
  database: simple_crawler
  username: root
  password: rootpass
