development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: rails_5_test
  username: root
  password: qwert1234
  host: localhost

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: rails_5_test_test
  username: root
  password: qwert1234
  host: localhost

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: simple_crawler
  username: root
  password: rootpass
  host: localhost